export const photoMatchCullConfig = {
  siteUrl: "https://ryanekoapp.web.id",
  supportEmail: "Ryan0eko0pram@gmail.com",
  privacyEmail: "Ryan0eko0pram@gmail.com",
  legalEmail: "Ryan0eko0pram@gmail.com",
  instagramUrl: "https://www.instagram.com/ryanekoapps",
  appStoreUrl: null as string | null,
  lastUpdated: { id: "14 Agustus 2026", en: "14 August 2026" },
} as const;

export type PhotoMatchCullLocale = "id" | "en";

const common = {
  id: {
    product: "Produk",
    support: "Bantuan",
    privacy: "Privasi",
    terms: "Ketentuan",
    developer: "Dikembangkan oleh Ryan Eko Apps",
    copyright: "Hak cipta dilindungi.",
    comingSoon: "Segera hadir di App Store",
    appStoreCta: "Unduh di App Store",
    lastUpdated: "Terakhir diperbarui",
    contents: "Daftar isi",
    backToTop: "Kembali ke atas",
  },
  en: {
    product: "Product",
    support: "Support",
    privacy: "Privacy",
    terms: "Terms",
    developer: "Developed by Ryan Eko Apps",
    copyright: "All rights reserved.",
    comingSoon: "Coming to the App Store",
    appStoreCta: "Download on the App Store",
    lastUpdated: "Last updated",
    contents: "Table of contents",
    backToTop: "Back to top",
  },
} as const;

const marketing = {
  id: {
    title: "Photo Match & Cull | Workflow RAW/JPEG untuk iPhone dan iPad",
    description: "Cocokkan nama JPEG pilihan dengan file RAW, salin atau pindahkan file yang sesuai, dan kelompokkan foto ke beberapa folder langsung dari iPhone dan iPad.",
    eyebrow: "Workflow foto untuk iPhone & iPad",
    headline: "Cocokkan file RAW dan rapikan hasil seleksi foto lebih cepat.",
    heroDescription: "Photo Match & Cull membantu fotografer mencocokkan nama JPEG pilihan dengan file RAW asli, menyalin atau memindahkan file yang cocok, dan mengelompokkan foto ke beberapa folder tujuan.",
    badges: ["Tersedia untuk iPhone dan iPad", "RAW Match", "Referensi Folder JPEG", "Folder Google Drive Publik", "Photo Culler 9 Folder", "Salin & Pindahkan", "Full Unlock Sekali Bayar"],
    supportCta: "Lihat Bantuan",
    privacyCta: "Kebijakan Privasi",
    highlightsEyebrow: "Dua workflow, satu aplikasi",
    highlightsTitle: "Dari hasil seleksi ke file siap kirim",
    features: [
      { title: "RAW Match", description: "Pilih folder sumber RAW dan folder tujuan, lalu masukkan nama file pilihan melalui daftar teks, folder referensi JPEG, atau link folder Google Drive publik. Aplikasi akan mencari file RAW yang cocok dan menyalin atau memindahkannya ke folder tujuan." },
      { title: "Beragam Format RAW", description: "Cari file kamera yang sesuai tanpa mengubah workflow penamaan file Anda." },
      { title: "Referensi Folder JPEG", description: "Gunakan nama file dari folder JPEG yang dipilih sebagai daftar referensi untuk menemukan file RAW pasangannya." },
      { title: "Referensi Google Drive Publik", description: "Tempel link folder Google Drive publik untuk membaca nama file sebagai referensi pencocokan. Aplikasi tidak membutuhkan login Google dan tidak mengunggah file ke Google Drive." },
      { title: "Photo Culler 9 Folder", description: "Tinjau foto dan tandai ke maksimal sembilan folder tujuan. Salin atau pindahkan JPEG bersama file RAW pasangannya." },
      { title: "Salin atau Pindahkan", description: "Salin file tanpa menghapus file asli, atau pindahkan file ke folder tujuan ketika sudah siap." },
    ],
    formatsTitle: "Format yang didukung",
    formatsDescription: "RAW Match mendukung format kamera populer dan file JPG.",
    howTitle: "Cara kerja",
    howDescription: "Pilih workflow yang sesuai dengan tahap seleksi foto Anda.",
    rawSteps: ["Pilih folder sumber RAW.", "Pilih folder tujuan.", "Pilih format RAW.", "Tambahkan nama file melalui Daftar Teks, Folder JPEG, atau Google Drive Publik.", "Ketuk Salin atau Pindahkan.", "Tinjau hasil pemrosesan."],
    cullerSteps: ["Pilih folder JPEG.", "Pilih folder RAW pasangan bila diperlukan.", "Atur folder tujuan.", "Tinjau dan tandai foto.", "Pilih Salin atau Pindahkan.", "Proses foto yang sudah ditandai."],
    compatibilityTitle: "Dirancang untuk iPhone dan iPad",
    compatibility: ["Menggunakan document picker native iOS", "File dan folder dipilih langsung oleh pengguna", "Mendukung tampilan potret dan lanskap", "Tidak membutuhkan akun aplikasi", "Full App Unlock melalui Apple In-App Purchase", "Restore Purchase tersedia di Settings"],
    freeTitle: "Coba gratis, buka akses penuh sekali bayar",
    freeDescription: "RAW Match dan Photo Culler masing-masing menyediakan 10 sesi pemrosesan gratis yang berhasil. Sesi hanya dihitung apabila setidaknya satu file berhasil diproses. Full App Unlock menghapus batas tersebut melalui satu kali Apple In-App Purchase.",
    localizedPrice: "Harga lokal ditampilkan di dalam aplikasi.",
    faqTitle: "Pertanyaan umum",
    faq: [
      ["Apa yang dihitung sebagai satu penggunaan gratis?", "Satu penggunaan dihitung ketika sebuah batch menghasilkan setidaknya satu file yang berhasil diproses."],
      ["Apakah proses gagal tetap dihitung?", "Tidak. Batch yang gagal seluruhnya atau dibatalkan tidak mengurangi kuota."],
      ["Bisakah Full App Unlock dipulihkan?", "Ya. Gunakan Restore Purchase dengan Apple Account yang sama dengan saat pembelian."],
      ["Apakah aplikasi mengunggah foto saya?", "Tidak. File foto lokal diproses di perangkat melalui folder yang Anda pilih."],
      ["Apakah mode Google Drive membutuhkan login?", "Tidak. Mode ini hanya membaca metadata atau nama file dari link folder Google Drive publik."],
      ["Format RAW apa yang didukung?", "ARW, CR2, CR3, NEF, NRW, RAF, RW2, ORF, PEF, DNG, dan JPG."],
      ["Apa perbedaan Salin dan Pindahkan?", "Salin mempertahankan file sumber. Pindahkan dapat menghapus file sumber setelah salinan tujuan berhasil dibuat."],
      ["Apa yang harus dilakukan sebelum memakai Pindahkan?", "Buat backup, pastikan ruang penyimpanan cukup, lalu periksa folder sumber dan tujuan."],
      ["Bisakah aplikasi dipakai di iPad?", "Ya. Photo Match & Cull dirancang untuk iPhone dan iPad dalam orientasi potret maupun lanskap."],
      ["Bagaimana cara menghubungi bantuan?", "Buka halaman Bantuan untuk solusi umum atau kirim email langsung ke Ryan Eko Apps."],
    ],
    finalTitle: "Seleksi selesai. RAW cocok. Folder rapi.",
    finalDescription: "Photo Match & Cull segera hadir untuk iPhone dan iPad.",
  },
  en: {
    title: "Photo Match & Cull | RAW/JPEG Workflow for iPhone and iPad",
    description: "Match selected JPEG filenames with RAW files, copy or move matching files, and organize photos into multiple folders directly on iPhone and iPad.",
    eyebrow: "Photo workflow for iPhone & iPad",
    headline: "Match RAW files and organize photo selections faster.",
    heroDescription: "Photo Match & Cull helps photographers match selected JPEG filenames with their original RAW files, copy or move matching files, and organize photos into multiple destination folders.",
    badges: ["Available for iPhone and iPad", "RAW Match", "JPEG Folder Reference", "Public Google Drive Folder", "9 Folder Photo Culler", "Copy & Move", "One-Time Full Unlock"],
    supportCta: "View Support",
    privacyCta: "Privacy Policy",
    highlightsEyebrow: "Two workflows, one app",
    highlightsTitle: "From photo selections to delivery-ready files",
    features: [
      { title: "RAW Match", description: "Choose a RAW source folder and destination folder, then provide selected filenames using a text list, a JPEG reference folder, or a public Google Drive folder link. The app finds matching RAW files and copies or moves them to the selected destination." },
      { title: "Multiple RAW Formats", description: "Find matching files from popular camera formats without changing your filename workflow." },
      { title: "JPEG Folder Reference", description: "Use filenames from a selected JPEG folder as the reference list for finding the corresponding RAW files." },
      { title: "Public Google Drive Reference", description: "Paste a public Google Drive folder link to read its filenames as the matching reference. The app does not require Google sign-in and does not upload files to Google Drive." },
      { title: "9 Folder Photo Culler", description: "Review photos and tag them into as many as nine destination folders. Copy or move JPEG files together with their associated RAW files." },
      { title: "Copy or Move", description: "Copy files while keeping the originals, or move them to the destination when you are ready." },
    ],
    formatsTitle: "Supported formats",
    formatsDescription: "RAW Match supports popular camera formats and JPG files.",
    howTitle: "How it works",
    howDescription: "Choose the workflow that matches your current photo-selection stage.",
    rawSteps: ["Select the RAW source folder.", "Select the destination folder.", "Choose the RAW formats.", "Add filenames using Text List, JPEG Folder, or Public Google Drive.", "Tap Copy or Move.", "Review the processing result."],
    cullerSteps: ["Select the JPEG folder.", "Optionally select the associated RAW folder.", "Configure destination folders.", "Review and tag photos.", "Choose Copy or Move.", "Process the tagged photos."],
    compatibilityTitle: "Designed for iPhone and iPad",
    compatibility: ["Uses the native iOS document picker", "Files and folders are selected explicitly by the user", "Supports portrait and landscape layouts", "No application account required", "Full App Unlock uses Apple In-App Purchase", "Restore Purchase is available from Settings"],
    freeTitle: "Try it free, then unlock once",
    freeDescription: "RAW Match and Photo Culler each include 10 successful free processing sessions. A session is counted only when at least one file is processed successfully. Full App Unlock removes these limits through a one-time Apple In-App Purchase.",
    localizedPrice: "Localized price shown in the app.",
    faqTitle: "Frequently asked questions",
    faq: [
      ["What counts as one free use?", "One use is counted when a batch successfully processes at least one file."],
      ["Are failed processes counted?", "No. Fully failed or cancelled batches do not reduce your allowance."],
      ["Can I restore Full App Unlock?", "Yes. Use Restore Purchase with the same Apple Account used for the purchase."],
      ["Does the app upload my photos?", "No. Local photo files are processed on the device through folders you select."],
      ["Does Google Drive mode require login?", "No. It only reads metadata or filenames from a public Google Drive folder link."],
      ["What RAW formats are supported?", "ARW, CR2, CR3, NEF, NRW, RAF, RW2, ORF, PEF, DNG, and JPG."],
      ["What is the difference between Copy and Move?", "Copy keeps the source file. Move may remove it after the destination copy succeeds."],
      ["What should I do before using Move?", "Create a backup, confirm available storage, and verify the source and destination folders."],
      ["Can I use the app on iPad?", "Yes. Photo Match & Cull is designed for iPhone and iPad in portrait and landscape."],
      ["How can I contact support?", "Visit the Support page for common solutions or email Ryan Eko Apps directly."],
    ],
    finalTitle: "Selections done. RAW files matched. Folders organized.",
    finalDescription: "Photo Match & Cull is coming soon to iPhone and iPad.",
  },
} as const;

const support = {
  id: {
    title: "Bantuan Photo Match & Cull | Ryan Eko Apps",
    description: "Temukan solusi umum dan hubungi Ryan Eko Apps untuk bantuan Photo Match & Cull.",
    heading: "Bantuan Photo Match & Cull",
    intro: "Butuh bantuan menggunakan Photo Match & Cull? Lihat solusi umum di bawah atau hubungi Ryan Eko Apps secara langsung.",
    contactTitle: "Hubungi bantuan",
    emailLabel: "Email bantuan",
    emailCta: "Kirim email",
    instagram: "Instagram Ryan Eko Apps",
    troubleshootingTitle: "Pemecahan masalah",
    troubleshooting: [
      ["Harga Full App Unlock tidak muncul", ["Periksa koneksi internet.", "Pastikan layanan App Store tersedia.", "Tutup dan buka kembali layar pembelian.", "Ketuk Retry Loading Product."]],
      ["Pembelian selesai tetapi akses masih terbatas", ["Buka Settings di dalam aplikasi.", "Pilih Restore Purchase.", "Pastikan perangkat memakai Apple Account yang sama."]],
      ["Tidak ada file RAW yang ditemukan", ["Periksa nama file dan ekstensi.", "Pastikan format RAW yang benar dipilih.", "Aktifkan Search Subfolders bila diperlukan.", "Pastikan JPEG dan RAW memiliki nama dasar yang sama."]],
      ["Folder tidak dapat diakses", ["Pilih kembali folder melalui document picker iOS.", "Pastikan penyedia folder mengizinkan akses baca/tulis."]],
      ["Folder Google Drive tidak dapat dipindai", ["Pastikan link folder bersifat publik.", "Pastikan URL mengarah ke folder Google Drive.", "Periksa koneksi internet."]],
      ["Operasi Salin atau Pindahkan gagal", ["Periksa kapasitas penyimpanan tujuan.", "Periksa izin folder.", "Jangan pilih folder sumber dan tujuan yang sama.", "Buat backup sebelum memakai Pindahkan."]],
    ],
    purchaseTitle: "Pembelian dan refund",
    purchaseBody: "Pembelian diproses oleh Apple. Untuk masalah tagihan atau permintaan refund, kunjungi website Report a Problem milik Apple.",
    reportCta: "Buka Report a Problem",
    usefulLinks: "Tautan penting",
  },
  en: {
    title: "Photo Match & Cull Support | Ryan Eko Apps",
    description: "Find common solutions and contact Ryan Eko Apps for help with Photo Match & Cull.",
    heading: "Photo Match & Cull Support",
    intro: "Need help with Photo Match & Cull? Review the common solutions below or contact Ryan Eko Apps directly.",
    contactTitle: "Contact support",
    emailLabel: "Support email",
    emailCta: "Send an email",
    instagram: "Ryan Eko Apps on Instagram",
    troubleshootingTitle: "Troubleshooting",
    troubleshooting: [
      ["Full App Unlock price does not appear", ["Check the internet connection.", "Make sure App Store services are available.", "Close and reopen the purchase screen.", "Tap Retry Loading Product."]],
      ["Purchase completed but access is still limited", ["Open Settings inside the app.", "Select Restore Purchase.", "Confirm the device uses the same Apple Account."]],
      ["No matching RAW files are found", ["Check the filename and extension.", "Confirm the correct RAW formats are selected.", "Check whether Search Subfolders is required.", "Verify that JPEG and RAW files share the same base filename."]],
      ["Folder cannot be accessed", ["Select the folder again through the iOS document picker.", "Verify that the folder provider allows read/write access."]],
      ["Google Drive folder cannot be scanned", ["Confirm the folder link is public.", "Make sure the URL is a Google Drive folder link.", "Check the internet connection."]],
      ["Copy or Move operation fails", ["Verify destination storage capacity.", "Check folder permissions.", "Avoid selecting the same source and destination folder.", "Create a backup before using Move."]],
    ],
    purchaseTitle: "Purchases and refunds",
    purchaseBody: "Purchases are processed by Apple. For billing problems or refund requests, visit Apple’s Report a Problem website.",
    reportCta: "Open Report a Problem",
    usefulLinks: "Useful links",
  },
} as const;

type LegalSection = { id: string; title: string; paragraphs: readonly string[] };

const privacySections: Record<PhotoMatchCullLocale, readonly LegalSection[]> = {
  id: [
    { id: "overview", title: "1. Ringkasan", paragraphs: ["Photo Match & Cull dikembangkan oleh Ryan Eko Apps untuk mengatur dan memindahkan file foto yang dipilih pengguna."] },
    { id: "account", title: "2. Tanpa akun aplikasi", paragraphs: ["Aplikasi tidak mewajibkan pengguna membuat akun dengan Ryan Eko Apps."] },
    { id: "local-files", title: "3. Akses file lokal", paragraphs: ["Aplikasi hanya mengakses file dan folder yang dipilih langsung melalui document picker iOS. File foto lokal diproses di perangkat. Ryan Eko Apps tidak menerima salinan foto lokal melalui server miliknya."] },
    { id: "google-drive", title: "4. Mode Google Drive publik", paragraphs: ["Jika pengguna memberikan link folder Google Drive publik, aplikasi berkomunikasi dengan Google Drive API untuk mengambil metadata atau nama file yang diperlukan untuk pencocokan.", "Aplikasi tidak memerlukan login Google dan tidak mengunggah file lokal ke Google Drive. Google dapat memproses informasi teknis sesuai kebijakan privasinya sendiri."] },
    { id: "purchases", title: "5. In-App Purchase", paragraphs: ["Pembelian dan informasi transaksi ditangani Apple melalui StoreKit. Ryan Eko Apps menerima status hak akses yang diperlukan untuk menentukan apakah Full App Unlock aktif. Informasi kartu pembayaran tidak diberikan kepada Ryan Eko Apps."] },
    { id: "counters", title: "6. Penghitung penggunaan gratis", paragraphs: ["Aplikasi menyimpan penghitung penggunaan RAW Match dan Photo Culler secara aman di perangkat menggunakan iOS Keychain. Penghitung ini dapat tetap tersimpan setelah aplikasi dipasang ulang dan hanya digunakan untuk menerapkan batas penggunaan gratis."] },
    { id: "notifications", title: "7. Notifikasi", paragraphs: ["Jika izin diberikan, aplikasi dapat mengirim notifikasi lokal saat pemrosesan selesai. Notifikasi tersebut tidak digunakan untuk iklan."] },
    { id: "analytics", title: "8. Analitik dan pelacakan", paragraphs: ["Aplikasi native saat ini tidak menyertakan iklan yang dioperasikan developer, analitik perilaku, atau pelacakan lintas aplikasi oleh Ryan Eko Apps."] },
    { id: "sharing", title: "9. Pembagian data", paragraphs: ["Ryan Eko Apps tidak menjual informasi pribadi pengguna. Apple memproses pembelian dan Google memproses permintaan API hanya ketika layanan terkait digunakan."] },
    { id: "children", title: "10. Anak-anak", paragraphs: ["Photo Match & Cull adalah utilitas workflow fotografi dan tidak ditujukan secara khusus kepada anak-anak."] },
    { id: "security", title: "11. Keamanan", paragraphs: ["Kami menerapkan perlindungan yang wajar sesuai sifat aplikasi. Namun, tidak ada metode penyimpanan atau transmisi elektronik yang sepenuhnya aman."] },
    { id: "changes", title: "12. Perubahan kebijakan", paragraphs: ["Kebijakan ini dapat diperbarui. Tanggal revisi terbaru akan selalu ditampilkan pada halaman ini."] },
    { id: "contact", title: "13. Kontak", paragraphs: [`Pertanyaan privasi dapat dikirim ke ${photoMatchCullConfig.privacyEmail}.`] },
  ],
  en: [
    { id: "overview", title: "1. Overview", paragraphs: ["Photo Match & Cull is developed by Ryan Eko Apps for organizing and transferring photo files selected by the user."] },
    { id: "account", title: "2. No application account", paragraphs: ["The app does not require users to create an account with Ryan Eko Apps."] },
    { id: "local-files", title: "3. Local file access", paragraphs: ["The app accesses only files and folders explicitly selected through the iOS document picker. Local photo files are processed on the device. Ryan Eko Apps does not receive copies of local photos through its own server."] },
    { id: "google-drive", title: "4. Public Google Drive mode", paragraphs: ["If users provide a public Google Drive folder link, the app communicates with the Google Drive API to retrieve file metadata or filenames required for matching.", "The app does not require Google login and does not upload local files to Google Drive. Google may process technical information according to Google’s own privacy policy."] },
    { id: "purchases", title: "5. In-App Purchases", paragraphs: ["Purchases and transaction information are handled by Apple through StoreKit. Ryan Eko Apps receives the entitlement status required to determine whether Full App Unlock is active. Payment card information is not provided to Ryan Eko Apps."] },
    { id: "counters", title: "6. Free-usage counters", paragraphs: ["The app stores RAW Match and Photo Culler usage counters securely on the device using the iOS Keychain. These counters may remain after reinstalling the app and are used only to enforce the free-use allowance."] },
    { id: "notifications", title: "7. Notifications", paragraphs: ["If permission is granted, the app may send local notifications about processing completion. These notifications are not used for advertising."] },
    { id: "analytics", title: "8. Analytics and tracking", paragraphs: ["The native app currently does not include developer-operated advertising, behavioral analytics, or cross-app tracking by Ryan Eko Apps."] },
    { id: "sharing", title: "9. Data sharing", paragraphs: ["Ryan Eko Apps does not sell users’ personal information. Apple processes purchases and Google processes API requests only when their respective services are used."] },
    { id: "children", title: "10. Children", paragraphs: ["Photo Match & Cull is a photography workflow utility and is not specifically directed at children."] },
    { id: "security", title: "11. Security", paragraphs: ["We apply reasonable safeguards appropriate to the nature of the app. However, no method of electronic storage or transmission is completely secure."] },
    { id: "changes", title: "12. Changes", paragraphs: ["This policy may be updated. The latest revision date will always be displayed on this page."] },
    { id: "contact", title: "13. Contact", paragraphs: [`Privacy questions may be sent to ${photoMatchCullConfig.privacyEmail}.`] },
  ],
};

const termsSections: Record<PhotoMatchCullLocale, readonly LegalSection[]> = {
  id: [
    { id: "acceptance", title: "1. Persetujuan ketentuan", paragraphs: ["Dengan mengunduh atau menggunakan Photo Match & Cull, pengguna menyetujui ketentuan ini dan perjanjian lisensi Apple yang berlaku."] },
    { id: "license", title: "2. Lisensi", paragraphs: ["Pengguna menerima lisensi terbatas, pribadi, non-eksklusif, dan tidak dapat dipindahtangankan untuk menggunakan aplikasi."] },
    { id: "responsibility", title: "3. Tanggung jawab pengguna", paragraphs: ["Pengguna bertanggung jawab memilih folder sumber dan tujuan yang benar serta harus memiliki izin untuk mengakses dan memproses file yang dipilih. Simpan backup, terutama sebelum menggunakan Pindahkan."] },
    { id: "operations", title: "4. Operasi Salin dan Pindahkan", paragraphs: ["Salin berupaya mempertahankan file asli. Pindahkan dapat menghapus file sumber setelah salinan tujuan berhasil. Pengguna harus memeriksa hasil dan ruang penyimpanan yang tersedia."] },
    { id: "drive-links", title: "5. Link Google Drive publik", paragraphs: ["Pengguna hanya boleh memberikan link yang berhak mereka akses dan proses. Link publik dapat ditangani Google berdasarkan ketentuannya."] },
    { id: "free-usage", title: "6. Penggunaan gratis", paragraphs: ["RAW Match dan Photo Culler masing-masing menyediakan hingga 10 sesi pemrosesan gratis yang berhasil. Sesi dihitung saat setidaknya satu file berhasil diproses. Batch yang gagal atau dibatalkan tidak dihitung. Penghitung disimpan di perangkat dan dapat bertahan setelah pemasangan ulang."] },
    { id: "unlock", title: "7. Full App Unlock", paragraphs: ["Full App Unlock adalah In-App Purchase non-consumable sekali bayar yang ditangani Apple. Harga ditampilkan Apple dalam mata uang lokal pengguna. Pembelian dapat dipulihkan dengan Apple Account yang sama. Sengketa tagihan dan refund mengikuti kebijakan Apple."] },
    { id: "acceptable-use", title: "8. Penggunaan yang diperbolehkan", paragraphs: ["Pengguna tidak boleh menyalahgunakan, merekayasa balik, mengganggu, atau memakai aplikasi untuk memproses file tanpa izin, kecuali hukum yang berlaku memperbolehkannya."] },
    { id: "availability", title: "9. Ketersediaan", paragraphs: ["Fitur dapat bergantung pada iOS, penyedia penyimpanan, layanan Apple, Google Drive, akses internet, atau ketersediaan pihak ketiga."] },
    { id: "disclaimer", title: "10. Penafian", paragraphs: ["Aplikasi disediakan sebagaimana tersedia. Kami tidak menjamin setiap pemindahan file akan selalu selesai tanpa gangguan atau kesalahan."] },
    { id: "liability", title: "11. Batasan tanggung jawab", paragraphs: ["Sejauh diizinkan hukum, Ryan Eko Apps tidak bertanggung jawab atas kehilangan data, transfer terputus, kehilangan keuntungan, atau kerugian tidak langsung yang timbul dari penggunaan aplikasi."] },
    { id: "changes", title: "12. Perubahan dan penghentian", paragraphs: ["Ryan Eko Apps dapat memperbarui aplikasi atau ketentuan ini. Pengguna dapat berhenti menggunakan dan menghapus aplikasi kapan saja."] },
    { id: "governing", title: "13. Ketentuan yang berlaku", paragraphs: ["Apple Standard EULA juga berlaku kecuali EULA khusus disediakan di App Store Connect. Ketentuan ini tidak membatasi hak konsumen wajib berdasarkan hukum yang berlaku."] },
    { id: "contact", title: "14. Kontak", paragraphs: [`Pertanyaan tentang ketentuan ini dapat dikirim ke ${photoMatchCullConfig.legalEmail}.`] },
  ],
  en: [
    { id: "acceptance", title: "1. Acceptance of terms", paragraphs: ["By downloading or using Photo Match & Cull, users agree to these terms and the applicable Apple license agreement."] },
    { id: "license", title: "2. License", paragraphs: ["Users receive a limited, personal, non-exclusive, non-transferable license to use the app."] },
    { id: "responsibility", title: "3. User responsibility", paragraphs: ["Users are responsible for selecting the correct source and destination folders and must have permission to access and process selected files. Maintain backups, especially before using Move."] },
    { id: "operations", title: "4. Copy and Move operations", paragraphs: ["Copy attempts to retain the original file. Move may remove the source file after a destination copy succeeds. Users must verify results and available storage."] },
    { id: "drive-links", title: "5. Public Google Drive links", paragraphs: ["Users may only provide links they are authorized to access and process. Public links may be handled by Google under Google’s terms."] },
    { id: "free-usage", title: "6. Free usage", paragraphs: ["RAW Match and Photo Culler each provide up to 10 successful free processing sessions. A session is counted when at least one file is processed successfully. Failed or cancelled batches are not counted. Usage counters are stored on the device and may persist after reinstall."] },
    { id: "unlock", title: "7. Full App Unlock", paragraphs: ["Full App Unlock is a one-time, non-consumable In-App Purchase handled by Apple. Pricing is shown by Apple in the user’s local currency. Purchases can be restored using the same Apple Account. Billing disputes and refund requests are subject to Apple’s policies."] },
    { id: "acceptable-use", title: "8. Acceptable use", paragraphs: ["Users may not misuse, reverse engineer, interfere with, or use the app to process files without authorization, except where applicable law permits otherwise."] },
    { id: "availability", title: "9. Availability", paragraphs: ["Features may depend on iOS, storage providers, Apple services, Google Drive, internet access, or third-party availability."] },
    { id: "disclaimer", title: "10. Disclaimer", paragraphs: ["The app is provided on an “as available” basis. We do not promise that every file transfer will always complete without interruption or error."] },
    { id: "liability", title: "11. Limitation of liability", paragraphs: ["To the extent permitted by law, Ryan Eko Apps is not liable for data loss, interrupted transfers, lost profits, or indirect damages arising from use of the app."] },
    { id: "changes", title: "12. Changes and termination", paragraphs: ["Ryan Eko Apps may update the application or these terms. Users may stop using and uninstall the app at any time."] },
    { id: "governing", title: "13. Governing terms", paragraphs: ["Apple’s Standard EULA also applies unless a custom EULA is provided in App Store Connect. These terms do not limit mandatory consumer protection rights under applicable law."] },
    { id: "contact", title: "14. Contact", paragraphs: [`Questions about these terms may be sent to ${photoMatchCullConfig.legalEmail}.`] },
  ],
};

const legal = {
  privacy: {
    id: { title: "Kebijakan Privasi Photo Match & Cull | Ryan Eko Apps", description: "Kebijakan privasi Photo Match & Cull mengenai file lokal, Google Drive, pembelian, dan data pengguna.", heading: "Kebijakan Privasi untuk Photo Match & Cull", sections: privacySections.id },
    en: { title: "Photo Match & Cull Privacy Policy | Ryan Eko Apps", description: "Photo Match & Cull privacy policy covering local files, Google Drive, purchases, and user data.", heading: "Privacy Policy for Photo Match & Cull", sections: privacySections.en },
  },
  terms: {
    id: { title: "Syarat & Ketentuan Photo Match & Cull | Ryan Eko Apps", description: "Syarat dan ketentuan penggunaan Photo Match & Cull.", heading: "Syarat & Ketentuan untuk Photo Match & Cull", sections: termsSections.id },
    en: { title: "Photo Match & Cull Terms & Conditions | Ryan Eko Apps", description: "Terms and conditions for using Photo Match & Cull.", heading: "Terms & Conditions for Photo Match & Cull", sections: termsSections.en },
  },
} as const;

export const photoMatchCullContent = { common, marketing, support, legal } as const;
